In [15]:
import pandas as pd
import numpy as np

In [16]:
pd.__version__

'2.3.1'

In [17]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [18]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [19]:
len(df) #to get number of rows or values

9704

In [20]:
df['fuel_type'].nunique()

2

In [21]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [22]:
df['fuel_efficiency_mpg'] 

0       13.231729
1       13.688217
2       14.246341
3       16.912736
4       12.488369
          ...    
9699    15.101802
9700    17.962326
9701    17.186587
9702    15.331551
9703    14.884467
Name: fuel_efficiency_mpg, Length: 9704, dtype: float64

In [23]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max().round(3)

np.float64(23.759)

In [24]:
df.horsepower.median()

np.float64(149.0)

In [25]:
hp_mode = df.horsepower.mode()[0]
print(hp_mode)

152.0


In [26]:
df['horsepower'] = df['horsepower'].fillna(hp_mode)

In [27]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower               0
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [28]:
df['horsepower'].median()

np.float64(152.0)

In [29]:
asia_car = df[df['origin'] == 'Asia']

In [30]:
asia_car[['vehicle_weight' , 'model_year']]

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [31]:
asia_car[['vehicle_weight' , 'model_year']].head(7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [32]:
X = asia_car[['vehicle_weight' , 'model_year']].head(7).values.round(2)

In [33]:
X

array([[2714.22, 2016.  ],
       [2783.87, 2010.  ],
       [3582.69, 2007.  ],
       [2231.81, 2011.  ],
       [2659.43, 2016.  ],
       [2844.23, 2014.  ],
       [3761.99, 2019.  ]])

In [34]:
X.T

array([[2714.22, 2783.87, 3582.69, 2231.81, 2659.43, 2844.23, 3761.99],
       [2016.  , 2010.  , 2007.  , 2011.  , 2016.  , 2014.  , 2019.  ]])

In [35]:
XTX = X.T.dot(X)

In [36]:
XTX

array([[62248346.87540001, 41431222.87      ],
       [41431222.87      , 28373339.        ]])

In [37]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [38]:
XTX_inv = np.linalg.inv(XTX)

In [39]:
w = (XTX_inv.dot(X.T)).dot(y)

In [40]:
w

array([0.01386366, 0.5049075 ])

In [41]:
w.sum().round(5)

np.float64(0.51877)