In [135]:
import pandas as pd
import numpy as np

In [136]:
pd.__version__

'2.3.1'

In [137]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [138]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [139]:
len(df) #to get number of rows or values

9704

In [140]:
df['fuel_type'].nunique()

2

In [141]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [142]:
df['fuel_efficiency_mpg'] 

0       13.231729
1       13.688217
2       14.246341
3       16.912736
4       12.488369
          ...    
9699    15.101802
9700    17.962326
9701    17.186587
9702    15.331551
9703    14.884467
Name: fuel_efficiency_mpg, Length: 9704, dtype: float64

In [143]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max().round(3)

np.float64(23.759)

In [144]:
df.horsepower.median()

np.float64(149.0)

In [145]:
hp_mode = df.horsepower.mode()
print(hp_mode)

0    152.0
Name: horsepower, dtype: float64


In [146]:
df['horsepower'] = df['horsepower'].fillna(152.0)

In [147]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower               0
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [148]:
df['horsepower'].median()

np.float64(152.0)

In [154]:
df[df['origin'] == 'Asia']

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0       152.0     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

In [155]:
df[['vehicle_weight' , 'model_year']]

vehicle_weight  model_year
0        3413.433759        2003
1        3149.664934        2007
2        3079.038997        2018
3        2542.392402        2009
4        3460.870990        2009
...              ...         ...
9699     2981.107371        2013
9700     2439.525729        2004
9701     2583.471318        2008
9702     2905.527390        2011
9703     2908.043477        2005

[9704 rows x 2 columns]

In [166]:
df[['vehicle_weight' , 'model_year']].head(7)

vehicle_weight  model_year
0     3413.433759        2003
1     3149.664934        2007
2     3079.038997        2018
3     2542.392402        2009
4     3460.870990        2009
5     2484.883986        2008
6     3006.542287        2012

In [167]:
X = df[['vehicle_weight' , 'model_year']].head(7).values.round(2)

In [168]:
X

array([[3413.43, 2003.  ],
       [3149.66, 2007.  ],
       [3079.04, 2018.  ],
       [2542.39, 2009.  ],
       [3460.87, 2009.  ],
       [2484.88, 2008.  ],
       [3006.54, 2012.  ]])

In [169]:
X.T

array([[3413.43, 3149.66, 3079.04, 2542.39, 3460.87, 2484.88, 3006.54],
       [2003.  , 2007.  , 2018.  , 2009.  , 2009.  , 2008.  , 2012.  ]])

In [170]:
XTX = X.T.dot(X)

In [171]:
XTX

array([[64707629.25709999, 42471317.48999999],
       [42471317.48999999, 28264752.        ]])

In [172]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

In [174]:
XTX_inv = np.linalg.inv(XTX)

In [177]:
w = (XTX_inv.dot(X.T)).dot(y)

In [182]:
w

array([0.07099481, 0.41931579])

In [184]:
w.sum().round(2)

np.float64(0.49)

In [185]:
df['fuel_efficiency_mpg'].max()

np.float64(25.96722204888372)